name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: 23f2000794@ds.study.iitm.ac.in - Print Hello World
      run: echo "Hello, world!"
